# Generated by Django 5.1.3 on 2024-11-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0003_alter_user_role_alter_user_is_active_delete_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventArea',
            new_name='Tickets',
        ),
    ]
