# Generated by Django 5.1.3 on 2024-11-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0004_rename_eventarea_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(related_name='events', to='EventManager.artist'),
        ),
        migrations.DeleteModel(
            name='ActingArtist',
        ),
    ]
